### ISSUE TITLE
How to redraw the table?

### ISSUE THREAD

**Issue by tampe125** [akottr/dragtable#29]
If I dynamically add more columns using Javascript, they are not sortable, since there's no event attached to them.
Looking at the code, I saw that there is a `redraw()` method. 
How can I invoke it? Is that necessary, or dragTable can understand when I'm binding the same widget to the same table and redraw it?

**Comment by periyasamy2git** [comment]
> Hi, this is how to invoke redraw:
> 
> ```js
> $('#mydragtable').dragtable('redraw');
> ```

This Not working dynamically added columns
