### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Mottie** [akottr/dragtable#36]
What exactly are the dependencies of this widget? And would you please include a list in the readme.

* jQuery
* jQuery UI
  * Core
  * Widget
  * Mouse
  * Sortable

Am I missing something from the above list?

**Comment by scriby** [comment]
+1

I'm trying to integrate this plugin into a webapp that doesn't already have jquery UI as a dependency and need to know what the minimal jquery UI configuration is.

**Comment by akottr** [comment]
@Mottie you are missing nothing.

* jQuery
* jQuery UI
  * Core
  * Widget
  * Mouse
  * Sortable

These are the dependencies.
