### ISSUE TITLE
dragtable problem with angular

### ISSUE THREAD

**Issue by Naxmeify** [akottr/dragtable#46]
seems ng-repeat (dynamic) rows and dragtable cannot work together :(

any suggestions?....

if i got one - i will say :8ball:

**Comment by scvinod** [comment]
Hi, did you get any?

**Comment by Naxmeify** [comment]
no - switched to https://github.com/Naxmeify/angular-dragtable

**Comment by scvinod** [comment]
Thanks. But I see this is not working in IE9.
